/**
 * What the three alarm tones ARE, as data.
 *
 * Kept apart from `sounds.ts` because that file carries `require()` calls for
 * the bundled audio, which only Metro can resolve. Every consumer that just
 * needs to know which tones exist — settings normalisation, the notification
 * service, the tests — imports this instead, and stays loadable anywhere.
 *
 * The tones themselves are generated by `scripts/make-sounds.py`.
 */

export type AlarmSoundId = 'soft' | 'normal' | 'sharp';

export type AlarmSoundSpec = {
  id: AlarmSoundId;
  /**
   * The bare filename, for the notification.
   *
   * Android copies these into res/raw at prebuild and looks them up by name,
   * so each string must match the `sounds` array in app.config.ts exactly.
   */
  file: string;
  /**
   * Whether the player fades this tone in rather than starting at full gain.
   *
   * Only the soft tone ramps. The whole point of the other two is that they
   * are at full strength from the first instant, and fading them in would
   * quietly undo the choice the user made.
   */
  ramps: boolean;
};

/** How long the soft tone takes to reach full gain. */
export const RAMP_MS = 4000;

/**
 * Order matters: this is the order they appear in settings, and it runs from
 * gentlest to harshest so the list itself explains the choice.
 */
export const ALARM_SOUND_IDS: readonly AlarmSoundId[] = ['soft', 'normal', 'sharp'] as const;

export const ALARM_SOUND_SPECS: Record<AlarmSoundId, AlarmSoundSpec> = {
  soft: { id: 'soft', file: 'alarm-soft.wav', ramps: true },
  normal: { id: 'normal', file: 'alarm-normal.wav', ramps: false },
  sharp: { id: 'sharp', file: 'alarm-sharp.wav', ramps: false },
};

export const DEFAULT_SOUND_ID: AlarmSoundId = 'normal';

export function isAlarmSoundId(value: unknown): value is AlarmSoundId {
  return typeof value === 'string' && value in ALARM_SOUND_SPECS;
}

/** Falls back to the default rather than throwing on a value read from disk. */
export function specFor(id: unknown): AlarmSoundSpec {
  return ALARM_SOUND_SPECS[isAlarmSoundId(id) ? id : DEFAULT_SOUND_ID];
}
